name: Backup Fork and Sync

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  backup-and-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write  # 明確添加 workflows 權限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global checkout.defaultRemote origin

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/microsoft/graphrag.git || git remote set-url upstream https://github.com/microsoft/graphrag.git
          git fetch --all --tags

      - name: Sync and handle conflicts
        run: |
          branches=$(git branch -r | grep 'origin/' | grep -v 'origin/HEAD' | sed 's/origin\///')
          
          for branch in $branches; do
            echo "Processing branch: $branch"
            
            if git ls-remote --exit-code --heads upstream $branch > /dev/null 2>&1; then
              git checkout -B $branch origin/$branch
              
              if git merge upstream/$branch --no-edit; then
                echo "Successfully merged changes for $branch"
                git push origin $branch
              else
                echo "Merge conflict in $branch. Attempting automatic resolution..."
                
                git diff --name-only --diff-filter=U | xargs git checkout --theirs
                git add .
                if git diff --staged --quiet; then
                  echo "No changes to commit after auto-resolution for $branch"
                  git merge --abort
                else
                  git commit -m "Auto-resolve conflicts in $branch"
                  
                  if git push origin $branch; then
                    echo "Pushed auto-resolved changes for $branch"
                  else
                    echo "Failed to push changes for $branch. Creating conflict marker commit."
                    git reset --soft HEAD~1
                    git commit -m "CONFLICT: Auto-resolution failed for $branch"
                    git push origin $branch
                  fi
                fi
              fi
            else
              echo "Branch $branch does not exist in upstream. Skipping."
            fi
          done

      - name: Create version tag
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          git tag -a "sync-$TIMESTAMP" -m "Sync on $TIMESTAMP"

      - name: Push tags
        run: |
          if git push --tags origin; then
            echo "Successfully pushed tags"
          else
            echo "Failed to push tags. This is non-critical, continuing workflow."
          fi

      - name: Generate sync report
        if: always()
        run: |
          echo "Sync Report" > sync_report.md
          echo "===========" >> sync_report.md
          echo "" >> sync_report.md
          git branch -r | grep 'origin/' | grep -v 'origin/HEAD' | sed 's/origin\///' | while read branch; do
            echo "## Branch: $branch" >> sync_report.md
            if git log HEAD..origin/$branch --oneline | grep -q .; then
              echo "Status: Changes pushed" >> sync_report.md
              echo "Changes:" >> sync_report.md
              git log HEAD..origin/$branch --oneline >> sync_report.md
            else
              echo "Status: No changes or sync failed" >> sync_report.md
            fi
            echo "" >> sync_report.md
          done

      - name: Upload sync report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sync-report
          path: sync_report.md
